<div align="center">

**LAPORAN PRAKTIKUM**

**STRUKTUR DATA**

**“Tipe Data dan Variabel”**

**Disusun Oleh :**

**Muhammad Nazril Fandhi**

**2611532034**

**Dosen Pengampu:**

**Wahyudi.DR.. S.T.M.T**

**Asisten Praktikum:**

**Sherly Sukmadira**

<br>

 <img src="images/logo_unand.png" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

## KATA PENGANTAR

Puji beserta syukur saya panjatkan atas kehadirat Tuhan Yang Maha Esa yang telah memberikan rahmat dan berkatnya, sehingga saya dapat menyelesaikan laporan praktikum mengenai pengenalan tipe data dan variabel Python yang telah dilaksanakan sebagai pertemuan ke-2 untuk mata kuliah Praktikum Algoritma dan Pemrograman. Praktikum ini berfokus pada pembahasan jenis - jenis tipe data yang ada pada bahasa pemrograman Python.

Melalui praktikum ini, hasil yang diharapkan adalah saya dapat memahami secara langsung konsep mengenai macam - macam tipe data Python dan bisa mengindentifikasi nilai dari suatu variabel serta bisa mengelompokkan nilai variabel berdasarkan tipe datanya pada bahasa pemrograman Python.

Penulis menyadari bahwa laporan praktikum ini masih memiliki banyak kekurangan. Oleh karena itu, kritik dan saran yang membangun sangat diharapkan demi perbaikan dan pengembangan di masa mendatang.

Padang, 2026

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang
Dalam dunia pemrograman, pemahaman terhadap konsep dasar merupakan fondasi yang wajib dikuasai sebelum mempelajari algoritma yang lebih kompleks. Salah satu konsep nya yaitu "Struktur Data", Tipe Data dan Variabel. Python dipilih sebagai bahasa pemrograman dalam praktikum ini karena cukup mudah dipelajari dengan sintaks yang sederhana.

Tipe data merupakan klasifikasi atau kategori dari suatu nilai yang menentukan jenis operasi apa saja yang dapat dilakukan terhadap data tersebut, serta berapa besar ruang memori yang dibutuhkan untuk menyimpannya. Beberapa tipe data dasar yang umum digunakan dalam bahasa pemrograman Python antara lain boolean (nilai benar atau salah), string (teks/karakter), float (bilangan desimal), integer (bilangan bulat).

Variabel berfungsi sebagai tempat untuk menyimpan nilai yang nantinya dapat digunakan kembali ketika program dijalankan. Dengan adanya variabel, data yang digunakan dalam program dapat disimpan dan diolah dengan lebih mudah.

Melalui praktikum ini, praktikan diharapkan dapat memahami cara menggunakan variabel, mengenali beberapa tipe data dasar, dan menerapkannya dalam program sederhana menggunakan Python.

## 1.2 Tujuan
1. Memahami konsep dasar variabel dalam pemrograman.
2. Mengenal berbagai jenis tipe data dasar dalam Python.
3. Mampu menerapkan konsep tipe data dan variabel dalam penyelesaian permasalahan sederhana melalui program Python.

## 1.3 Manfaat
1. Dapat memahami dasar-dasar pemrograman menggunakan Python.
2. Meningkatkan kemampuan menulis kode program Python dengan lebih baik, terstruktur, dan minim kesalahan (error).
3. Memahami cara menemukan dan menangani kesalahan pada program.

---
# BAB II
# PEMBAHASAN

## 2.1 Dasar Teori

    1. Pengenalan Bahasa Python
Python merupakan salah satu bahasa pemrograman tingkat tinggi (high-level programming language) yang bersifat general-purpose, artinya dapat digunakan untuk berbagai keperluan pengembangan perangkat lunak, mulai dari aplikasi desktop, web, analisis data, kecerdasan buatan (artificial intelligence), hingga machine learning. Python memiliki bentuk penulisan yang relatif sederhana sehingga mudah dibaca dan dipelajari. Python diciptakan oleh Guido van Rossum dan pertama kali dirilis pada tahun 1991.

    2. Variabel
Variabel adalah suatu identitas atau nama yang digunakan untuk menyimpan suatu nilai (data) di dalam memori komputer, di mana nilai tersebut dapat diakses, diubah, maupun digunakan kembali selama program dijalankan. Variabel dapat dianalogikan sebagai sebuah "wadah" yang menampung data tertentu. Dalam penulisannya, variabel memiliki beberapa aturan seperti tidak boleh mengandung spasi atau simbol khusus seperti @, #, % dan hanya boleh terdiri dari huruf, angka, dan garis bawah.

    3. Tipe Data
Tipe data menunjukkan bentuk atau jenis nilai yang terdapat pada suatu variabel. Python memiliki beberapa tipe data bawaan yang sering digunakan antara lain:
- Integer (int): tipe data untuk bilangan bulat, baik positif maupun negatif, tanpa mengandung angka desimal.

- Float (float): tipe data untuk bilangan pecahan atau desimal.

- String (str): tipe data untuk kumpulan karakter atau teks, yang dituliskan di antara tanda kutip tunggal ('...') atau tanda kutip ganda ("...").

- Boolean (bool): menyimpan nilai logika yang terdiri dari True dan False.


## 2.2 Kode Program

### 2.2.1 Program "Boolean_2611532034"

In [14]:
# Buat file dengan nama Boolean_NIM.py
# Nama variabel ditambah 4 digit nim terakhir contoh: nilai_1234
# Deklarasi variabel dengan tipe data Boolean
is_lulus_2034 = True
is_cumlaude_2034 = True

# Menggunakan Boolean
nilai_2034 = 85
batas_lulus_2034 = 75

# Menentukan nilai Boolean dari kondisi
status_kelulusan_2034 = nilai_2034 >= batas_lulus_2034 # Hasilnya akan True

print("=== Check Kelulusan ===")
print("Nilai:", nilai_2034)
print("Apakah Lulus?:", status_kelulusan_2034)
if is_lulus_2034 and is_cumlaude_2034:
    print("Selamat Anda lulus dengan predikat cumlaude!")

=== Check Kelulusan ===
Nilai: 85
Apakah Lulus?: True
Selamat Anda lulus dengan predikat cumlaude!


**Penjelasan :**
1. Dua variabel pertama berisi nilai Boolean untuk menunjukkan status lulus dan status cumlaude.
2. nilai_2034 menyimpan nilai mahasiswa, sedangkan batas_lulus_2034 menyimpan nilai minimum untuk dinyatakan lulus.
3. Perbandingan kedua nilai tersebut menghasilkan True atau False pada variabel status kelulusan.
4. Hasil akhirnya ditampilkan ke layar menggunakan beberapa perintah print().

### 2.2.2 Program "Input_2611532034"

In [15]:
# Buat file dengan nama Input_NIM.py
# Buat program untuk menghitung luas persegi panjang
# Nama variabel ditambah 4 digit nim terakhir contoh: panjang_1234
# Program ini menggunakan fungsi input() untuk meminta pengguna
# memasukkan panjang dan lebar persegi panjang.
# Nilai yang dimasukkan akan dikonversi menjadi tipe data integer
panjang_2034 = input("Masukkan panjang: 5")
lebar_2034 = input("Masukkan lebar: 10")
luas_2034 = int(panjang_2034) * int(lebar_2034)
print("Luas = ", luas_2034)

Luas =  50


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk meminta pengguna memasukkan nilai panjang dan lebar persegi panjang menggunakan fungsi input().
2. Kedua input diubah menjadi bilangan integer, lalu dikalikan untuk mendapatkan luas.
3. Hasil luas yang sudah dihitung ditampilkan pada layar.

### 2.2.3 Program "Konstanta_2611532034"

In [11]:
# Buat file dengan nama Konstanta_NIM.py
# Program ini menggunakan konstanta untuk menghitung luas lingkaran
# nama variabel ditambah 4 digit nim terakhir contoh: jari_1234

from typing import Final
PI: Final = 3.14
print("pi: %f" % (PI))
jari_2034 = float(input('10'))
luas_2034 = PI * jari_2034 * jari_2034
print("Luas lingkaran dengan jari-jari %.2f adalah %.2f" % (jari_2034, luas_2034))

pi: 3.140000
Luas lingkaran dengan jari-jari 10.00 adalah 314.00


**Penjelasan :**
1. Program mengimpor Final dan menetapkan PI dengan nilai 3.14 sebagai konstanta.
2. Nilai PI ditampilkan, kemudian pengguna diminta memasukkan jari-jari lingkaran.
3. Nilai jari-jari digunakan bersama PI untuk menghitung luas lingkaran.
4. Hasil perhitungan ditampilkan dengan dua angka di belakang koma.

### 2.2.4 Program "Numerik_2611532034"

In [16]:
# Buat file dengan nama Numerik_NIM.py
# nama variabel ditambah 4 digit terakhir NIM contoh: a_5500
#create a variable with integer value.
a_2034=100
print("The type of variable having value", a_2034, " is ", type (a_2034))

#create a variable with float value.
b_2034=10.2345
print("The type of variable having value", b_2034, " is ", type (b_2034))

#create a variable with complex value.
c_2034=100+3j
print("The type of variable having value", c_2034, " is ", type (c_2034))

The type of variable having value 100  is  <class 'int'>
The type of variable having value 10.2345  is  <class 'float'>
The type of variable having value (100+3j)  is  <class 'complex'>


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk membuat variabel a_2034 dengan nilai 100 dan menampilkan nilai serta tipe datanya menggunakan fungsi type().
2. Bagian 3 sampai 4 berfungsi untuk membuat variabel b_2034 dengan nilai 10.2345 dan menampilkan nilai serta tipe datanya.
3. Bagian 5 sampai 6 berfungsi untuk membuat variabel c_2034 dengan nilai kompleks 100+3j dan menampilkan nilai serta tipe datanya.

### 2.2.5 Program "String_2611532034"

In [18]:
# Buat file dengan nama String_NIM.py
#nama variabel ditambah 4 digit nim terakhir contoh: nama_1234
#ganti program nya dan data masing-masing
nama_2034 ="Muhammad Nazril Fandhi_2611532034"
jenis_kelamin_2034 = 'L'
alamat_2034 = """
    Asrama Unand
    Kec.pauh
    Kota Padang
"""
agama_2034 = 'islam'
print ("Nama saya adalah: ", nama_2034)
print ("Jenis kelamin saya adalah: ", jenis_kelamin_2034)
print ("Alamat saya adalah: ", alamat_2034)
print ("Agama saya adalah: ", agama_2034)

Nama saya adalah:  Muhammad Nazril Fandhi_2611532034
Jenis kelamin saya adalah:  L
Alamat saya adalah:  
    Asrama Unand
    Kec.pauh
    Kota Padang

Agama saya adalah:  islam


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk membuat variabel nama_2034 dan jenis_kelamin_3003 yang menyimpan data nama dan jenis kelamin.
2. Bagian 3 sampai 7 berfungsi untuk membuat variabel alamat_2034 yang menyimpan data alamat dalam bentuk string yang terdiri dari beberapa baris.
3. Bagian 8 berfungsi untuk membuat variabel agama_2034 yang menyimpan data agama.
4. Bagian 9 sampai 12 berfungsi untuk menampilkan nama, jenis kelamin, alamat, dan agama ke layar menggunakan fungsi print().

---
## Tugas Praktikum

**Soal :**

<div align="center">
<img src="images/ss soal.PNG" width="500"><br>
<em>Gambar 2.2 : Soal Tugas Praktikum</em>
</div>

**Kode Jawaban :**

a. Kode Program "Tugas2_2611532034"

In [ ]:
from typing import Final
BATAS_LULUS: Final = 75.0

print("=== SISTEM REGISTRASI PRAKTIKAN ALPRO 2026 ===")
nama_2034 = input("Masukkan Nama: ")
jenis_kelamin_2034 = input("Masukkan Jenis Kelamin (L/P): ")
umur_2034 = int(input("Masukkan Umur: "))
skor_2034 = float(input("Masukkan Skor Tes Awal: "))
print("        ")
print("=== DATA PRAKTIKAN & HASIL PEMERIKSAAN ===")
alamat_2034 = """
Asrama Unand,
Kec.Pauh,
Kota Padang"""
print("Nama Mahasiswa:", nama_2034, "| Tipe:", type(nama_2034))
print("Jenis Kelamin:", jenis_kelamin_2034, "| Tipe:", type(jenis_kelamin_2034))
print("Alamat Domisili: ", alamat_2034, "| Tipe:", type(alamat_2034))
print("Umur:", umur_2034, "| Tipe:", type(umur_2034))
print("Skor Tes Awal:", skor_2034, "| Tipe:", type(skor_2034))
token_2034 = 100+3j
print("ID Token Sinyal:", token_2034, "| Tipe:", type(token_2034))
print("        ")
print("=== STATUS KELULUSAN PRAKTIKUM ===")
print("Batas Minimum Nilai:", BATAS_LULUS, "| Tipe:", type(BATAS_LULUS))
print("Apakah Lulus?:", skor_2034 >= BATAS_LULUS, "| Tipe:", type(skor_2034 >= BATAS_LULUS))

**Output :**

<div align="center">
<img src="images/output2.PNG" width="400"><br>
<em>Gambar 2.3 : Output Tugas Praktikum</em>
</div>

**Penjelasan :** Program tugas ini mencatat identitas praktikan dan melakukan verifikasi status kelulusan awal praktikum secara otomatis setelah menerima input dari pengguna

---
# BAB III
# KESIMPULAN

Berdasarkan praktikum yang telah dilakukan, beberapa hal dapat disimpulkan bahwa Python mempunyai aturan penulisan yang cukup sederhana sehingga cocok untuk mempelajari dasar pemrograman dan membuat program dengan berbagai kebutuhan seperti Struktur Data: Tipe Data dan Variabel.

Dalam konteks pemrograman, Fungsi type() dapat digunakan untuk mengidentifikasi tipe data dari suatu variabel, sedangkan fungsi seperti int(), float(), str(), dan bool() dapat digunakan untuk melakukan konversi tipe data (type casting) sesuai kebutuhan program.

---
## DAFTAR PUSTAKA

[1] GeeksforGeeks. (2024). Python Data Types. https://www.geeksforgeeks.org/python-data-types/

[2] Real Python. (2024). Basic Data Types in Python. https://realpython.com/python-data-types/

[3] Lubanovic, B. (2019). Introducing Python: Modern Computing in Simple Packages (2nd ed.). O'Reilly Media. https://www.oreilly.com/library/view/introducing-python-2nd/9781492051374/

[4] ​Matthes, E. (2019). Python Crash Course: A Hands-On, Project-Based Introduction to Programming (2nd ed.). No Starch Press. https://nostarch.com/pythoncrashcourse2e